INFO - 1401/04/13-8:40:36 - UI object for setting app created.
------------------------------------------------------------------------------
INFO - 1401/04/13-8:40:36 - UI object initialized and setting app loaded.
------------------------------------------------------------------------------
INFO - 1401/04/13-8:40:36 - Creating API object.
------------------------------------------------------------------------------
INFO - 1401/04/13-8:40:36 - Login UI object initialized.
------------------------------------------------------------------------------
INFO - 1401/04/13-8:40:36 - Confirmaton UI object initialized.
------------------------------------------------------------------------------
INFO - 1401/04/13-8:40:36 - Notficaion UI object initialized.
------------------------------------------------------------------------------
INFO - 1401/04/13-8:40:36 - Connected to MySQL Server version 8.0.29
------------------------------------------------------------------------------
INFO - 1401/04/13-8:40:36 - Connected to database [('saba_database',)]
------------------------------------------------------------------------------
INFO - 1401/04/13-8:40:36 - MySQL connection is closed
------------------------------------------------------------------------------
INFO - 1401/04/13-8:40:36 - Login API object initialized.
------------------------------------------------------------------------------
INFO - 1401/04/13-8:40:36 - Connected to MySQL Server version 8.0.29
------------------------------------------------------------------------------
INFO - 1401/04/13-8:40:36 - Connected to database [('saba_database',)]
------------------------------------------------------------------------------
INFO - 1401/04/13-8:40:36 - MySQL connection is closed
------------------------------------------------------------------------------
INFO - 1401/04/13-8:40:36 - Database object initialized.
------------------------------------------------------------------------------
INFO - 1401/04/13-8:40:37 - Get available camera serials using camera-connecton API.
------------------------------------------------------------------------------
WARNING - 1401/04/13-8:40:37 - Some Cameras are not connected.
------------------------------------------------------------------------------
INFO - 1401/04/13-8:40:37 - Timer for checking storage initialized.
------------------------------------------------------------------------------
INFO - 1401/04/13-8:40:42 - User logined with username: ali.
------------------------------------------------------------------------------
INFO - 1401/04/13-8:40:44 - Camera params are loaded from database camera-id: 1
------------------------------------------------------------------------------
INFO - 1401/04/13-8:40:45 - Camera settings applied to databse
------------------------------------------------------------------------------
INFO - 1401/04/13-8:40:48 - Connected to camera, serial: 23905933
------------------------------------------------------------------------------
INFO - 1401/04/13-8:40:56 - Disconnected from camera, serial: 23905933
------------------------------------------------------------------------------
INFO - 1401/04/13-8:40:58 - Connected to camera, serial: 23905933
------------------------------------------------------------------------------
INFO - 1401/04/13-8:41:1 - Disconnected from camera, serial: 23905933
------------------------------------------------------------------------------
ERROR - 1401/04/13-8:41:18 - Failed to connected to camera
------------------------------------------------------------------------------
Traceback (most recent call last):
  File "d:\SettingApp_oxin\backend\camera_connection.py", line 136, in start_grabbing
    self.camera.Open()
  File "C:\Users\Dorsa-PC4\AppData\Local\Programs\Python\Python39\lib\site-packages\pypylon\pylon.py", line 3329, in Open
    return _pylon.InstantCamera_Open(self)
_genicam.RuntimeException: Failed to open 'Basler acA1920-40gc#0030533B998D#169.254.142.153:3956'. The device is controlled by another application. Err: An attempt was made to access an address location which is currently/momentary not accessible. (0xE1018006)
 : RuntimeException thrown (file 'gigedevice.cpp', line 288)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\SettingApp_oxin\backend\camera_funcs.py", line 347, in connect_disconnect_camera
    cam_connection.start_grabbing()
  File "d:\SettingApp_oxin\backend\camera_connection.py", line 237, in start_grabbing
    print("An exception occurred.", e.GetDescription())
AttributeError: 'RuntimeException' object has no attribute 'GetDescription'
