INFO - 1401/04/12-16:48:54 - UI object for setting app created.
------------------------------------------------------------------------------
INFO - 1401/04/12-16:48:54 - UI object initialized and setting app loaded.
------------------------------------------------------------------------------
INFO - 1401/04/12-16:48:54 - Creating API object.
------------------------------------------------------------------------------
INFO - 1401/04/12-16:48:54 - Login UI object initialized.
------------------------------------------------------------------------------
INFO - 1401/04/12-16:48:54 - Confirmaton UI object initialized.
------------------------------------------------------------------------------
INFO - 1401/04/12-16:48:54 - Notficaion UI object initialized.
------------------------------------------------------------------------------
INFO - 1401/04/12-16:48:54 - Connected to MySQL Server version 8.0.29
------------------------------------------------------------------------------
INFO - 1401/04/12-16:48:54 - Connected to database [('saba_database',)]
------------------------------------------------------------------------------
INFO - 1401/04/12-16:48:54 - MySQL connection is closed
------------------------------------------------------------------------------
INFO - 1401/04/12-16:48:54 - Login API object initialized.
------------------------------------------------------------------------------
INFO - 1401/04/12-16:48:54 - Connected to MySQL Server version 8.0.29
------------------------------------------------------------------------------
INFO - 1401/04/12-16:48:54 - Connected to database [('saba_database',)]
------------------------------------------------------------------------------
INFO - 1401/04/12-16:48:54 - MySQL connection is closed
------------------------------------------------------------------------------
INFO - 1401/04/12-16:48:54 - Database object initialized.
------------------------------------------------------------------------------
INFO - 1401/04/12-16:48:55 - Get available camera serials using camera-connecton API.
------------------------------------------------------------------------------
WARNING - 1401/04/12-16:48:55 - Some Cameras are not connected.
------------------------------------------------------------------------------
INFO - 1401/04/12-16:48:55 - Timer for checking storage initialized.
------------------------------------------------------------------------------
INFO - 1401/04/12-16:49:4 - User logined with username: ali.
------------------------------------------------------------------------------
INFO - 1401/04/12-16:49:6 - Camera params are loaded from database camera-id: 1
------------------------------------------------------------------------------
ERROR - 1401/04/12-16:49:10 - Failed to connected to camera
------------------------------------------------------------------------------
Traceback (most recent call last):
  File "d:\SettingApp_oxin\backend\camera_connection.py", line 181, in start_grabbing
    self.camera.GevSCPSPacketSize.SetValue(int(self.ps)+1000)
  File "C:\Users\Dorsa-PC4\AppData\Local\Programs\Python\Python39\lib\site-packages\pypylon\genicam.py", line 2159, in SetValue
    return _genicam.IInteger_SetValue(self, Value, Verify)
_genicam.OutOfRangeException: The difference between Value = 1010 and Min = 220 must be dividable without rest by Inc = 4. : OutOfRangeException thrown in node 'GevSCPSPacketSize' while calling 'GevSCPSPacketSize.SetValue()' (file 'integert.h', line 79)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\SettingApp_oxin\backend\camera_funcs.py", line 334, in connect_disconnect_camera
    cam_connection.start_grabbing()
  File "d:\SettingApp_oxin\backend\camera_connection.py", line 235, in start_grabbing
    print("An exception occurred.", e.GetDescription())
AttributeError: 'OutOfRangeException' object has no attribute 'GetDescription'
INFO - 1401/04/12-16:49:56 - Camera settings applied to databse
------------------------------------------------------------------------------
ERROR - 1401/04/12-16:49:58 - Failed to connected to camera
------------------------------------------------------------------------------
Traceback (most recent call last):
  File "d:\SettingApp_oxin\backend\camera_connection.py", line 181, in start_grabbing
    self.camera.GevSCPSPacketSize.SetValue(int(self.ps)+1000)
  File "C:\Users\Dorsa-PC4\AppData\Local\Programs\Python\Python39\lib\site-packages\pypylon\genicam.py", line 2159, in SetValue
    return _genicam.IInteger_SetValue(self, Value, Verify)
_genicam.OutOfRangeException: The difference between Value = 1010 and Min = 220 must be dividable without rest by Inc = 4. : OutOfRangeException thrown in node 'GevSCPSPacketSize' while calling 'GevSCPSPacketSize.SetValue()' (file 'integert.h', line 79)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\SettingApp_oxin\backend\camera_funcs.py", line 334, in connect_disconnect_camera
    cam_connection.start_grabbing()
  File "d:\SettingApp_oxin\backend\camera_connection.py", line 235, in start_grabbing
    print("An exception occurred.", e.GetDescription())
AttributeError: 'OutOfRangeException' object has no attribute 'GetDescription'
INFO - 1401/04/12-16:51:19 - Setting app closed.
------------------------------------------------------------------------------
